### ISSUE TITLE
Chatbot iterating duplicate responses after every utterances

### ISSUE THREAD

**Issue by MustaqAhamed** [cbartram/ChatBot#2]
Hi Christian,

Hope you're well!

The chatbot after deploying locally in the system, is iterating the responses in a series like 1,2,3,4, and n after each utterance.
Could you check and provide details on how to update the code in the server.js file?

Thanks in advance!

![image](https://github.com/cbartram/ChatBot/assets/44725818/88aa8edb-965d-4e7f-98ce-4a0b452afc4c)

**Comment by omgitsfaraaz** [comment]
You can replace line **no. 134** by this:
`this.setState({ messages: [...messages, { user: res.user, type: res.type, text: res.msg, color: '#f1f0f0', timestamp: res.timestamp }] })
`
and comment out line **no. 139**.

**Comment by MustaqAhamed** [comment]
Thanks @omgitsfaraaz !

Its working now!
